---
title: "Blog 3"
subtitle: "Data For Equity"
description: How principles for advancing equitable data practice are relevant to our data
author: "Team 12"
date: "2024-04-01"
date-modified: "2024-04-01"
draft: FALSE
---
# Transparency: Be transparent about the limits of the data

A limitation of data is making analyses that the data does not support. In order to mitigate any unsupported analyses, it is important to be transparent about what data is being used and the process of arriving at the conclusion. Transparency is a relevant limitation to our data set since transparency is a necessity and missing quality in all data sets. One potential for abuse or misuse of our data set is how the data was collected. The data set mainly aims to understand the opportunity levels of children within the 100 largest metros in the US. For this reason, it is possible to make a conclusion that children outside the largest metros have lower health and environment opportunities. However, this would be an unsupported analysis since there is not enough data in the data set to confidently make that conclusion. Another limitation of the data is the z-score measurements. It is unclear what the exact measurements went into calculating the z-score. By not knowing the process of calculating the z-scores, it creates ambiguity and uncertainty when analyzing the score. Urban Institute, as mentioned earlier in this paragraph, emphasizes the importance of being transparent throughout the data collection and analysis process for the reason that it shows validity and credibility. Additionally, by adhering to the practice of being transparent, we can reduce the number of unreliable analyses and more accurately relay our findings to our audience.

# Data Collection: Avoid undue burden
Ensuring justice in the data collection process is crucial for any data collection. According to the guiding principles for data collection, data collection should reflect respect for the rights of individuals and community groups and minimize undue burden—in other words, eliminate the collection of nonessential elements. Implementing justice in the collection would require a thorough review of the data collection methodology to identify and eliminate unnecessary burdens. It requires regularly reviewing the necessity and usage of collected data elements, ensuring that only relevant data are retained and used. While avoiding undue burdens for the individuals and communities being surveyed is an ethical method for data collection, this also helps maintain cleaner data since it is constantly being checked, and irrelevant data will not be included. Although it is important to adhere to this principle, there are potential limitations to avoiding collecting information deemed too sensitive for certain individuals or groups. It might sound counter-intuitive as the principle asks to prevent unnecessary data collection, but one cannot be entirely sure what data is irrelevant before doing the analysis. Adhering to the justice principle could lead to limitations such as data availability, the potential for certain neighborhoods to be misrepresented, or the index's inability to capture every nuance of child development environments. The principle itself is an action to reduce abuse and misuse of the data; adhering to this principle would entail not only careful presentation and interpretation of the data but also guidance on its ethical use to inform policy and intervention without reinforcing negative stereotypes or inequalities.

# Accessability: Return data and research results to community members in a form they can use
Ensuring that our findings are accessible to people whose data we’ve analyzed is ethically important. After performing our data analysis and finding trends in the data, if valuable, we might share our findings with the creators of the Child Opportunity Index (COI), the Kirwan Institute for the Study of Race and Ethnicity at Ohio State University. This information may also be valuable to nonprofits. Sharing our findings with local governments may also be important, so that assistance programs may be able to specifically target areas with low CO indexes. It would be crucial to publish findings on public or free platforms to promote accessibility.
