---
title: "Blog 1"
subtitle: "3 Datasets"
description: Summary of 3 datasets 
author: "Team 12"
date: "2024-02-28"
date-modified: "2024-02-28"
draft: FALSE
---
Dataset 1:https://data.diversitydatakids.org/dataset/coi20-child-opportunity-index-2-0-database/resource/080cfe52-90aa-4925-beaa-90efb04ab7fb
  
  The Child Opportunity Index 2.0 database measures neighborhood resources
  and conditions affecting children’s development and access to opportunities.
  They used census data from 2015. (Indexes based on the 2010 census are
  also available.) We will be able to clean the data (though it seems quite
  clean already). There are 144,408 entries/rows. To better understand
  the racial demographics of these zip codes, we will need to find the
  zip codes with the lowest opportunity scores and independently find the
  racial demographics of these zip codes. Race data is not included in this
  dataset. A question we hope to explore is which of the 29 indicators in
  the Child Opportunity Index 2.0 database was the greatest predictor of
  opportunity score? If not measuring based only on one of the indicators,
  which of the three domains these indicators fall within (education,
  health and environment, and social and economic) is the best predictor
  of overall score? Another question we are interested in is based on
  the 10 zip codes with the lowest composite opportunity scores, and the
  10 highest. How do the racial demographics of these two groups differ?

Dataset 2: https://www.kaggle.com/datasets/rishidamarla/arrests-by-race
  
  "Arrests by Race" has 19 columns and 31 rows. The rows show the cause for
  arrest, some being more violent than others. The columns show the total of
  different racial groups. The data was collected to gain an understanding
  on number of persons arrested nationwide in 2018 broken down by race and
  ethnicity. We would be able to load and clean (if needed further cleaning)
  the dataset to analyze the data. This dataset only shows people arrested
  by law enforcement that provided their racial demographics. Therefore, it
  is important to note that the totals for each race may be different than
  the ethnicity totals. In addition, the data only represents the person
  arrested and not how many times that person was arrested. A question we
  hope to explore is are minority races charged with offenses more than White
  people? Another question is are Black people more likely to get arrested
  than White people for loitering (or also suspicion) crimes? 

Dataset 3:https://www.census.gov/programs-surveys/ces/data/public-use-data/race-and-economic-opportunity-data-tables.html
  
  The data comes from race and economic opportunity. Most previous work on
  racial disparities has studied inequality within a single generation of
  people. However, this datasets illustrate the racial gaps among generations.
  Using de-identified data covering 20 million children and their parents, the
  data shows how race currently shapes opportunity in the U.S. and how we can
  reduce racial disparities going forward. Specially, this data illustrates
  National Statistics by Parent Income Percentile, Gender, and Race. For the
  analysis of this data, it is necessary for us to interpret and understand the
  variables. There are 69 variables and we need to identify the dummy variables
  like gender. For different race, such as Asian, Black, hisp etc. Those data
  are ranked by income rank. With various kinds of combination, the data can
  be very messy. We are thinking about filter out the gender and emphasize the
  impact of different races. There are different outcomes of those children.
  Going to college, get married or getting in to prison. I believe those are
  categorical variable and maybe we can convert them into numerical variables
  to see if there is a correlation between children's outcome and parents'
  incomes and races.
